const users = [
  {
    name: "Emily Davis",
    email: "emilydavis@example.com",
    sex: "female",
    country: "United Kingdom",
    hobbies: ["reading", "painting", "travelling"],
    status: "active",
    education_level: "Bachelor's degree",
    age: 25,
    marital_status: "single",
    date_joined: "2021-08-15",
  },
  {
    name: "Alexis Garcia",
    email: "alexisgarcia@example.com",
    sex: "female",
    country: "United States",
    hobbies: ["reading", "hiking", "photography", "yoga"],
    status: "active",
    education_level: "Master's degree",
    age: 28,
    marital_status: "single",
    date_joined: "2019-05-10",
  },
  {
    name: "James Collins",
    email: "jamescollins@example.com",
    sex: "male",
    country: "United Kingdom",
    hobbies: [
      "playing guitar",
      "sailing",
      "painting",
      "travelling",
      "photography",
    ],
    status: "active",
    education_level: "Bachelor's degree",
    age: 31,
    marital_status: "engaged",
    date_joined: "2021-07-15",
  },
  {
    name: "Hannah Lee",
    email: "hannahlee@example.com",
    sex: "female",
    country: "United States",
    hobbies: ["reading", "watching movies", "cooking", "gardening"],
    status: "inactive",
    education_level: "Associate degree",
    age: 23,
    marital_status: "single",
    date_joined: "2020-09-23",
  },
  {
    name: "David Wilson",
    email: "davidwilson@example.com",
    sex: "male",
    country: "Nigeria",
    hobbies: ["playing basketball", "watching football", "travelling"],
    status: "suspended",
    education_level: "Bachelor's degree",
    age: 27,
    marital_status: "married",
    date_joined: "2018-03-01",
  },
  {
    name: "Aisha Abubakar",
    email: "aishaabubakar@example.com",
    sex: "female",
    country: "Nigeria",
    hobbies: ["swimming", "listening to music", "dancing"],
    status: "active",
    education_level: "High school",
    age: 19,
    marital_status: "single",
    date_joined: "2022-02-10",
  },
  {
    name: "David Johnson",
    email: "davidjohnson@example.com",
    sex: "male",
    country: "United States",
    hobbies: ["playing basketball", "watching movies", "cooking"],
    status: "inactive",
    education_level: "Master's degree",
    age: 29,
    marital_status: "single",
    date_joined: "2019-10-10",
  },
  {
    name: "Aisha Bello",
    email: "aishabello@example.com",
    sex: "female",
    country: "Nigeria",
    hobbies: ["reading", "swimming", "playing chess"],
    status: "suspended",
    education_level: "High school diploma",
    age: 20,
    marital_status: "single",
    date_joined: "2022-02-02",
  },
  {
    name: "Matthew Brown",
    email: "matthewbrown@example.com",
    sex: "male",
    country: "United Kingdom",
    hobbies: ["playing soccer", "watching movies", "travelling", "cooking"],
    status: "active",
    education_level: "Associate's degree",
    age: 27,
    marital_status: "married",
    date_joined: "2018-12-05",
  },
  {
    name: "Jennifer Wilson",
    email: "jenniferwilson@example.com",
    sex: "female",
    country: "United States",
    hobbies: ["reading", "playing tennis", "watching movies"],
    status: "inactive",
    education_level: "Doctorate degree",
    age: 38,
    marital_status: "married",
    date_joined: "2020-02-28",
  },
  {
    name: "Abdullahi Ahmed",
    email: "abdullahiahmed@example.com",
    sex: "male",
    country: "Nigeria",
    hobbies: [
      "playing video games",
      "watching soccer",
      "travelling",
      "swimming",
    ],
    status: "suspended",
    education_level: "Bachelor's degree",
    age: 24,
    marital_status: "single",
    date_joined: "2021-11-18",
  },
  {
    name: "Catherine Jordan",
    email: "CatherineJordan@yahoo.com",
    sex: "female",
    country: "United States",
    hobbies: ["reading", "hiking", "playing video games", "watching movies"],
    status: "active",
    education_level: "Bachelor's degree",
    age: 23,
    marital_status: "single",
    date_joined: "2019-05-18",
  },
  {
    name: "Peter Lee",
    email: "PeterLee@gmail.com",
    sex: "male",
    country: "United Kingdom",
    hobbies: ["playing basketball", "listening to music", "cooking"],
    status: "inactive",
    education_level: "High school diploma",
    age: 31,
    marital_status: "married",
    date_joined: "2021-11-07",
  },
  {
    name: "Chidi Nwosu",
    email: "ChidiNwosu@hotmail.com",
    sex: "male",
    country: "Nigeria",
    hobbies: ["watching soccer", "reading", "playing chess"],
    status: "suspended",
    education_level: "Master's degree",
    age: 40,
    marital_status: "married",
    date_joined: "2022-02-23",
  },
  {
    name: "Megan Thomas",
    email: "MeganThomas@yahoo.com",
    sex: "female",
    country: "United States",
    hobbies: ["painting", "running", "playing guitar", "traveling"],
    status: "active",
    education_level: "Associate's degree",
    age: 28,
    marital_status: "engaged",
    date_joined: "2020-06-12",
  },
  {
    name: "David Adekunle",
    email: "DavidAdekunle@gmail.com",
    sex: "male",
    country: "Nigeria",
    hobbies: ["playing soccer", "reading", "watching movies", "swimming"],
    status: "active",
    education_level: "Doctorate degree",
    age: 35,
    marital_status: "married",
    date_joined: "2021-02-28",
  },
  {
    name: "Benjamin Lee",
    email: "benjaminlee@example.com",
    sex: "male",
    country: "United States",
    hobbies: [
      "hiking",
      "watching documentaries",
      "playing video games",
      "travelling",
    ],
    status: "active",
    education_level: "Bachelor's degree",
    age: 31,
    marital_status: "engaged",
    date_joined: "2019-06-21",
  },
  {
    name: "Amaka Uche",
    email: "amakauche@example.com",
    sex: "female",
    country: "Nigeria",
    hobbies: ["reading", "playing volleyball", "watching movies"],
    status: "inactive",
    education_level: "High school diploma",
    age: 22,
    marital_status: "single",
    date_joined: "2021-03-09",
  },
  {
    name: "Liam Patel",
    email: "liampatel@example.com",
    sex: "male",
    country: "United Kingdom",
    hobbies: ["playing cricket", "watching sports", "cooking", "travelling"],
    status: "active",
    education_level: "Master's degree",
    age: 33,
    marital_status: "married",
    date_joined: "2018-11-11",
  },
  {
    name: "Sophie Jackson",
    email: "sophiejackson@example.com",
    sex: "female",
    country: "United States",
    hobbies: ["painting", "playing piano", "travelling"],
    status: "inactive",
    education_level: "Bachelor's degree",
    age: 26,
    marital_status: "engaged",
    date_joined: "2020-08-02",
  },
  {
    name: "Ahmed Ibrahim",
    email: "ahmedibrahim@example.com",
    sex: "male",
    country: "Nigeria",
    hobbies: ["watching soccer", "playing video games", "swimming"],
    status: "suspended",
    education_level: "Associate's degree",
    age: 23,
    marital_status: "single",
    date_joined: "2022-01-07",
  },
  {
    name: "Ella Wilson",
    email: "ellawilson@example.com",
    sex: "female",
    country: "United Kingdom",
    hobbies: ["playing tennis", "watching movies", "reading"],
    status: "active",
    education_level: "Doctorate degree",
    age: 37,
    marital_status: "married",
    date_joined: "2018-05-28",
  },
  {
    name: "Amina Ali",
    email: "aminaali@example.com",
    sex: "female",
    country: "Nigeria",
    hobbies: ["reading", "cooking", "travelling"],
    status: "active",
    education_level: "Bachelor's degree",
    age: 27,
    marital_status: "married",
    date_joined: "2020-11-14",
  },
  {
    name: "Nathan Liu",
    email: "nathanliu@example.com",
    sex: "male",
    country: "United States",
    hobbies: ["playing guitar", "watching sports", "travelling"],
    status: "active",
    education_level: "High school diploma",
    age: 24,
    marital_status: "single",
    date_joined: "2021-08-07",
  },
  {
    name: "Mariam Ahmed",
    email: "mariamahmed@example.com",
    sex: "female",
    country: "Nigeria",
    hobbies: ["dancing", "reading", "travelling"],
    status: "inactive",
    education_level: "Master's degree",
    age: 29,
    marital_status: "engaged",
    date_joined: "2019-05-01",
  },
  {
    name: "George Green",
    email: "georgegreen@example.com",
    sex: "male",
    country: "United Kingdom",
    hobbies: ["playing football", "watching movies", "travelling"],
    status: "active",
    education_level: "Bachelor's degree",
    age: 28,
    marital_status: "single",
    date_joined: "2018-07-03",
  },
  {
    name: "Hannah Kim",
    email: "hannahkim@example.com",
    sex: "female",
    country: "United States",
    hobbies: ["playing volleyball", "watching documentaries", "reading"],
    status: "suspended",
    education_level: "Doctorate degree",
    age: 41,
    marital_status: "married",
    date_joined: "2019-02-19",
  },
  {
    name: "Benjamin Lee",
    email: "benjaminlee@example.com",
    sex: "male",
    country: "United States",
    hobbies: ["playing basketball", "watching TV shows", "travelling"],
    status: "active",
    education_level: "Associate degree",
    age: 22,
    marital_status: "single",
    date_joined: "2022-01-10",
  },
  {
    name: "Abigail Peters",
    email: "abigailpeters@example.com",
    sex: "female",
    country: "United Kingdom",
    hobbies: ["playing piano", "painting", "travelling"],
    status: "inactive",
    education_level: "Bachelor's degree",
    age: 33,
    marital_status: "married",
    date_joined: "2020-06-02",
  },
  {
    name: "James Wang",
    email: "jameswang@example.com",
    sex: "male",
    country: "United States",
    hobbies: ["playing video games", "watching movies", "travelling"],
    status: "suspended",
    education_level: "High school diploma",
    age: 20,
    marital_status: "single",
    date_joined: "2020-06-02",
  },
];

export default users;
